// Round-trip self-test for the layer-anonymized Dark DEX W=128 VK.
//
// This exercises the production path end-to-end: it feeds the three
// `dark_dex_anonymized_layer_hashes_w128_L{0,1,2}` fixtures (generated by
// `gosh-dark-dex-halo2-new-circuit::dark_dex_circuit_new_layer_anonymized
//   ::test_export_tvm_sdk_data_layer_anonymized_w128`) into the TVM
// engine's `ZKHALO2VERIFY` opcode, which deserializes the embedded
// anonymized VK via `build_dark_dex_w128_vk()`.
//
// Catches accidental VK/proof drift: if `DARK_DEX_W128_VK_BYTES`
// gets out of sync with the circuit that produced the fixtures, all three
// positive tests fail. The wrong-instances + bad-proof tests guard against
// false-positive "everything verifies" regressions.

use std::time::Instant;

use tvm_types::SliceData;

use crate::executor::engine::Engine;
use crate::executor::test_helper::*;
use crate::executor::zk_halo2::execute_halo2_proof_verification;
use crate::stack::Stack;
use crate::stack::StackItem;
use crate::stack::savelist::SaveList;
use crate::utils::pack_data_to_cell;

const ANON_L0_PROOF_PATH: &str =
    "halo2_test_data/dark_dex_anonymized_layer_hashes_w128_L0_proof.bin";
const ANON_L0_INSTANCES_PATH: &str =
    "halo2_test_data/dark_dex_anonymized_layer_hashes_w128_L0_instances.bin";
const ANON_L1_PROOF_PATH: &str =
    "halo2_test_data/dark_dex_anonymized_layer_hashes_w128_L1_proof.bin";
const ANON_L1_INSTANCES_PATH: &str =
    "halo2_test_data/dark_dex_anonymized_layer_hashes_w128_L1_instances.bin";
const ANON_L2_PROOF_PATH: &str =
    "halo2_test_data/dark_dex_anonymized_layer_hashes_w128_L2_proof.bin";
const ANON_L2_INSTANCES_PATH: &str =
    "halo2_test_data/dark_dex_anonymized_layer_hashes_w128_L2_instances.bin";

fn setup_engine() -> Engine {
    let elector_code = load_boc("benches/elector-code.boc");
    let elector_data = load_boc("benches/elector-data.boc");
    let config_data = load_boc("benches/config-data.boc");
    let mut ctrls = SaveList::default();
    ctrls.put(4, &mut StackItem::Cell(elector_data)).unwrap();
    let params = vec![
        StackItem::int(0x76ef1ea),
        StackItem::int(0),
        StackItem::int(0),
        StackItem::int(1633458077),
        StackItem::int(0),
        StackItem::int(0),
        StackItem::int(0),
        StackItem::tuple(vec![StackItem::int(1000000000), StackItem::None]),
        StackItem::slice(
            SliceData::from_string(
                "9fe0000000000000000000000000000000000000000000000000000000000000001_",
            )
            .unwrap(),
        ),
        StackItem::cell(config_data.reference(0).unwrap()),
        StackItem::None,
        StackItem::int(0),
    ];
    ctrls.put(7, &mut StackItem::tuple(vec![StackItem::tuple(params)])).unwrap();
    let stack = Stack::new();
    Engine::with_capabilities(DEFAULT_CAPABILITIES).setup_with_libraries(
        SliceData::load_cell_ref(&elector_code).unwrap(),
        Some(ctrls),
        Some(stack),
        None,
        vec![],
    )
}

fn verify_proof(proof_path: &str, instances_path: &str) -> (bool, u128) {
    let mut engine = setup_engine();

    let pub_inputs_bytes =
        std::fs::read(instances_path).expect("Failed to read instances file");
    let pub_inputs_cell = pack_data_to_cell(&pub_inputs_bytes, &mut 0).unwrap();
    engine.cc.stack.push(StackItem::cell(pub_inputs_cell));

    let proof_bytes = std::fs::read(proof_path).expect("Failed to read proof file");
    let proof_cell = pack_data_to_cell(&proof_bytes, &mut 0).unwrap();
    engine.cc.stack.push(StackItem::cell(proof_cell));

    let start = Instant::now();
    let _ = execute_halo2_proof_verification(&mut engine).unwrap();
    let elapsed = start.elapsed().as_millis();

    let res = engine.cc.stack.get(0).as_bool().unwrap();
    (res, elapsed)
}

// ---------------------------------------------------------------------------
// Positive tests: each fixture must verify against the embedded anonymized VK.
// ---------------------------------------------------------------------------

#[test]
fn test_verify_anonymized_w128_l0() {
    let (res, elapsed) = verify_proof(ANON_L0_PROOF_PATH, ANON_L0_INSTANCES_PATH);
    println!("AnonW128L0 (0 chain steps): result={}, elapsed={}ms", res, elapsed);
    assert!(res, "L0 anonymized proof must verify against embedded VK");
}

#[test]
fn test_verify_anonymized_w128_l1() {
    let (res, elapsed) = verify_proof(ANON_L1_PROOF_PATH, ANON_L1_INSTANCES_PATH);
    println!("AnonW128L1 (1 chain step): result={}, elapsed={}ms", res, elapsed);
    assert!(res, "L1 anonymized proof must verify against embedded VK");
}

#[test]
fn test_verify_anonymized_w128_l2() {
    let (res, elapsed) = verify_proof(ANON_L2_PROOF_PATH, ANON_L2_INSTANCES_PATH);
    println!("AnonW128L2 (2 chain steps): result={}, elapsed={}ms", res, elapsed);
    assert!(res, "L2 anonymized proof must verify against embedded VK");
}

// ---------------------------------------------------------------------------
// Negative tests: corrupted instances or proof must fail.
// ---------------------------------------------------------------------------

#[test]
fn test_verify_anonymized_w128_wrong_instances() {
    let mut engine = setup_engine();

    let mut pub_inputs_bytes =
        std::fs::read(ANON_L0_INSTANCES_PATH).expect("Failed to read instances file");
    pub_inputs_bytes[0] ^= 0xFF;
    let pub_inputs_cell = pack_data_to_cell(&pub_inputs_bytes, &mut 0).unwrap();
    engine.cc.stack.push(StackItem::cell(pub_inputs_cell));

    let proof_bytes = std::fs::read(ANON_L0_PROOF_PATH).expect("Failed to read proof file");
    let proof_cell = pack_data_to_cell(&proof_bytes, &mut 0).unwrap();
    engine.cc.stack.push(StackItem::cell(proof_cell));

    let _ = execute_halo2_proof_verification(&mut engine).unwrap();
    let res = engine.cc.stack.get(0).as_bool().unwrap();
    assert!(!res, "Flipped instance byte must fail verification");
}

#[test]
fn test_verify_anonymized_w128_bad_proof() {
    let mut engine = setup_engine();

    let pub_inputs_bytes =
        std::fs::read(ANON_L0_INSTANCES_PATH).expect("Failed to read instances file");
    let pub_inputs_cell = pack_data_to_cell(&pub_inputs_bytes, &mut 0).unwrap();
    engine.cc.stack.push(StackItem::cell(pub_inputs_cell));

    let mut proof_bytes =
        std::fs::read(ANON_L0_PROOF_PATH).expect("Failed to read proof file");
    proof_bytes[10] ^= 0xFF;
    proof_bytes[20] ^= 0xFF;
    let proof_cell = pack_data_to_cell(&proof_bytes, &mut 0).unwrap();
    engine.cc.stack.push(StackItem::cell(proof_cell));

    let _ = execute_halo2_proof_verification(&mut engine).unwrap();
    let res = engine.cc.stack.get(0).as_bool().unwrap();
    assert!(!res, "Corrupted proof bytes must fail verification");
}

#[test]
fn test_verify_anonymized_w128_mismatched_proof_and_instances() {
    // L0 proof with L1 instances — should fail.
    let (res, _elapsed) = verify_proof(ANON_L0_PROOF_PATH, ANON_L1_INSTANCES_PATH);
    assert!(!res, "L0 proof + L1 instances must fail verification");
}
