[package]
name = "tls_check"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen-rt = { version = "0.41.0", features = ["bitflags"] }
num-bigint = "0.2.2"
num-traits = "0.2.8"
num-integer = "0.1.46"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "docs:adder"

[package.metadata.component.dependencies]

[workspace]
